### ISSUE TITLE
Missing parameter estimate in paper plot

### ISSUE THREAD

**Issue by jamesuanhoro** [rempsyc/lavaanExtra#14]
For some reason, the nice_lavaanPlot() output (https://github.com/rempsyc/lavaanExtra/blob/main/paper/paper_files/figure-latex/nice_lavaanPlot-2.pdf) in the JOSS paper is missing the estimate from ageyr to speed. I don't think I'm looking at it wrong, lol

**Comment by rempsyc** [comment]
Good catch. This is because only significant coefficients appear by default. I mention this in the paragraph below but I forgot to mention it in the function documentation. I will go add it now!

**Comment by rempsyc** [comment]
This reuses the `sig` argument from `lavaanPlot`, but with a .05 default. To make all coefficients appear, one can set `sig` to 1.

**Comment by jamesuanhoro** [comment]
Got it, I missed that. Thank you.
