### ISSUE TITLE
missing menu item in Example lavaan models

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#17]
For review: https://github.com/openjournals/joss-reviews/issues/5701

In the floating menu on this page:
https://lavaanextra.remi-theriault.com/articles/example.html
There are links only to the first 6 examples. Example 7 (total effects) seems to be omitted.

**Comment by rempsyc** [comment]
Thank you! This has been fixed and users can now use the navigation menu properly.
