### ISSUE TITLE
Feature: nice_fit; write χ² over chi2

### ISSUE THREAD

**Issue by Buedenbender** [rempsyc/lavaanExtra#2]
Hi Rémi,

I did not watch in the code, but I just recognized in experimenting with your package that you write 
in the heading of nice_table (inside nice_fit) "chi2" rather than  χ² . 

![grafik](https://user-images.githubusercontent.com/38650857/187020895-2bed4d80-6a5e-4be2-b488-3cb64e4d7705.png)

As I know this can be a pain with R-Cmd-Check failing with non ASCII characters from my
[flex_table1 function](https://buedenbender.github.io/datscience/reference/flex_table1.html) I might can help.

Try using the following string instead of Chi2
`"\u03C7\u00B2"`

Should result in  χ²

**Comment by rempsyc** [comment]
Could you try updating to the latest rempsyc version? That’s where this newly added conversion happens

**Comment by Buedenbender** [comment]
Ok perfekt that fixed it
