### ISSUE TITLE
name arguments in write_lavaan() examples

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#23]
For review: openjournals/joss-reviews#5701

The order of arguments in `write_lavaan()` is rather arbitrary.  That is not a bad thing (I see no reason why any particular order would be favored).  But the vignettes sometimes include examples where the model components are passed without naming the arguments:
https://lavaanextra.remi-theriault.com/articles/fullworkflow.html#sem-example

This might give readers the false impression that they can pass them in any order.

**Comment by rempsyc** [comment]
Hum, good point. Perhaps it would be interesting to find a way that users can pass the arguments in any order, but the trade-off is that it would require users to always name the passed lists in a specific way. Which I think could be more constraining (if users define those objects elsewhere) than having to name the arguments explicitly. For now, I have simply named the arguments throughout the vignettes and README. Thank you.
