### ISSUE TITLE
replace "special cases" with a write_lavaan() vignette

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#27]
For review: openjournals/joss-reviews#5701

The [Special Cases vignette](https://lavaanextra.remi-theriault.com/articles/special.html) is not very well motivated, and uses only one example, which makes the floating menu on the right seem unnecessary.

You might consider making a write_lavaan.Rmd vignette that describes each `write_lavaan()` argument in a separate section, then simply link to examples of its use in other vignettes/[examples](https://lavaanextra.remi-theriault.com/articles/example.html). For example:

- [Example 4.6](https://lavaanextra.remi-theriault.com/articles/example.html#example-4-6) already illustrates (in)equality constraints
- [Example 5](https://lavaanextra.remi-theriault.com/articles/example.html#example-5-mediation) illustrates user-defined parameters
- The [ML-SEM example](https://lavaanextra.remi-theriault.com/articles/example.html#example-6-multilevel-sem) illustrates the necessity of `write_lavaan(..., custom=)`
- You could reproduce the examples from lavaan's [mean-structures tutorial](https://lavaan.ugent.be/tutorial/means.html) in the examples.Rmd vignette, which illustrate the use of `write_lavaan(..., intercepts=)`, and then link to that in the write_lavaan.Rmd vignette
- There is no `write_lavaan(..., thresholds=)` argument, so currently specifying those would require the `custom=` argument as well.  This would be a good place to show users that.

This would then be a more exhaustive documentation for the `write_lavaan()` function, which you can link to in **See also** on the write_lavaan.Rd help page.

**Comment by rempsyc** [comment]
Thanks. Done. I have deleted the Special cases vignette and replaced it with one called "How to use `write_lavaan()`" linking to other vignettes as you suggested. I could not find a good example for showcasing thresholds with the "|" operator online. Do you know of any simple example?

**Comment by TDJorgensen** [comment]
Wow, I forgot how sparse lavaan's documentation is for thresholds, even on the `?model.syntax` help page.  Because they are typically "nuisance parameters" or at least not of any substantive interest (like residual variances), they are rarely included directly in model syntax.  I have some simple 2-variable examples here using simulated data, just to demonstrate how threshold models work:

https://tdjorgensen.github.io/TDJorgensen/CatMeasEq/Jorgensen.CatMeasEq.pdf

But a more substantively interesting example will probably always be more complex (typically, imposing invariance constraints).  Here is an example for longitudinal invariance:

https://thechangelab.stanford.edu/tutorials/growth-modeling/modeling-change-latent-vars-ordinal-indicators-lavaan/

Given that it builds up model components by adding equality constraints, it might make a good widely-applicable example to show how your approach would work for evaluating invariance assumptions (as I mentioned in #31).

**Comment by rempsyc** [comment]
Oh, great, thanks. Do I have your permission to reuse your examples and linking to those files as the source?

**Comment by TDJorgensen** [comment]
Yes
