### ISSUE TITLE
clarify target audience

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#30]
For review: openjournals/joss-reviews#5701

Regarding the paper:

I don't think the Statement of Need "clearly identifies ... who the target audience is", which is on the checklist.  It refers to "beginners" and "advanced users", without clarifying whether these are beginners or advanced users of SEM, of R, or of lavaan in particular.  After going through all of the examples, I can't find a reason to recommend it to my students who are learning SEM.  The only reason I would expect to use it myself (or recommend it to colleagues) would be for the nice looking tables, since the figures are simply wrappers around functions already available in other packages.

**Comment by rempsyc** [comment]
Thank you, I have revised the first paragraph as such:

> {lavaan} [@lavaanPackage] is a very popular R package for structural
> equation modeling (SEM). The package relies on specific operators to define
> latent variables, regressions, covariances, indirect effects, and so on.
> However, some individuals (e.g,. beginners to R and {lavaan}) may prefer 
> not having to specify the operators themselves, or would like to see some 
> steps automatized, such as defining indirect effects. Furthermore, for 
> researchers, it can be relatively difficult to extract relevant statistical 
> outputs in the form of tables and figures that are suitable for scientific 
> publication.

And I am open to further suggestions for improvement.
