### ISSUE TITLE
demonstrating the value of the plot wrappers

### ISSUE THREAD

**Issue by TDJorgensen** [rempsyc/lavaanExtra#32]
For review: openjournals/joss-reviews#5701

Regarding the paper:

Beginning on p. 4, there is a comparison of the default plots from `lavaanPlot()` and `nice_lavaanPlot()`, but the source code look like it only overrides a few defaults.  There is nothing inherently better or worse about a "naked" path diagram.  It would be helpful for users to see how much time `nice_lavaanPlot()` saves them by providing the `lavaanPlot()` syntax that would yield the same figure as provided by `nice_lavaanPlot()` by default.

Likewise for showing the `tidySEM::graph_sem()` that yields the default `nice_tidySEM()` plot.  Judging from the source code, I imagine `nice_tidySEM()` saves quite some space for users!

**Comment by rempsyc** [comment]
Thank you! Done. Although it lengthens the paper, I agree that it is both transparent whilst more explicitly showing the utility. In the case of tidySEM for example, it is not only about the number of lines of code, but also knowing which functions to use to generate the desired output. There are also other arguments that are FALSE by default but that also save time should they be used relative to the original functions, but I think that would be too much for the paper (JOSS papers are supposed to be short and mine is already longer than usual).
